work_dir: /data/wangkun/project/work_dir/LowQSAR/stgcn/ntu120/1014-1

# feeder
feeder: feeder.feeder_skeleton.Feeder
train_feeder_args:
  data_path: /data/wangkun/project/datasets/NTU_dataset/ntu120/NTU120_CSet.npz
  dataset: 'ntu'
  split: train
  window_size: 64
  random_rot: False
  random_shear: 0.3
  resize_crop: True
  random_crop: False
  p_interval: [0.5, 1]
  vel: False
  bone: False
  coordinate_transfer_type: 888
  normalization: -1
  vertical: True
  fixed_direction: True
  padding_none: True
  preprocess: True
test_feeder_args:
  data_path: /data/wangkun/project/datasets/NTU_dataset/ntu120/NTU120_CSet.npz
  dataset: 'ntu'
  split: test
  resize_crop: True
  random_crop: False
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  coordinate_transfer_type: 888
  normalization: -1
  vertical: True
  fixed_direction: True
  padding_none: True
  preprocess: True

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 120
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu'
    strategy: 'spatial'


weight_decay: 0.0001
base_lr: 0.001
optimizer: 'Adam'
lr_decay_type: 'cosine'
end_cosine_lr: 0.0001
device: [0]
batch_size: 128
test_batch_size: 32
num_epoch: 50
#warmup_epoch: 10
seed: -1
eval_interval: 5
save_interval: 50
bool_save_model: True
bool_save_checkpoint: False